### ISSUE TITLE
Count number of occurences

### ISSUE THREAD

**Issue by seryrzu** [Intsights/PySubstringSearch#1]
Hello,

Is there a way to count the number of occurrences of the query in target strings?
For example, if I do
```
writer = pysubstringsearch.Writer(
    index_file_path='output.idx',
)

writer.add_entry('string_string')
writer.finalize()
reader = pysubstringsearch.Reader(
    index_file_path='output.idx',
)
```

and I then
```
reader.number_of_occurences('str')
```
I would want to receive `2`. Can I do it?
My (indexes) text is very large (hundreds of millions of characters) and queries are rather large too (can be up to a million character).

Thanks

**Comment by wavenator** [comment]
Definetly!
I will implement it in the upcoming days and close this issue when its done. Thanks for the idea!
